import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Add these types to window object since they're loaded via script tags in some environments
// but here we imported them. However to be safe with TypeScript:
declare module "jspdf" {
    interface jsPDF {
        lastAutoTable: { finalY: number };
    }
}

export async function generateAssessmentPDF(data: any) {
    const { document, vehicle, pricing } = data;
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString("id-ID");

    // --- HEADER ---
    doc.setFontSize(18);
    doc.setTextColor(19, 91, 236); // Primary Blue
    doc.text("PEGADAIAN AI ANALYTICS", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${timestamp}`, 14, 26);
    doc.text(`ID: ${crypto.randomUUID().slice(0, 8).toUpperCase()}`, 14, 31);
    doc.line(14, 35, 196, 35);

    let finalY = 40;

    // --- 1. DOCUMENT ANALYSIS ---
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("1. Document Analysis", 14, finalY);
    finalY += 8;

    if (document) {
        const docData = [
            ["Full Name", document.fullName || "-"],
            ["Document Type", document.documentType || "-"],
            ["Credit Status", document.creditStatus || "-"],
            ["Income Range", document.incomeRange || "-"],
            ["Employment", document.employmentStatus || "-"],
            ["AI Confidence", `${Math.round((document.rawConfidence || 0) * 100)}%`],
        ];

        autoTable(doc, {
            startY: finalY,
            head: [["Field", "Value"]],
            body: docData,
            theme: 'striped',
            headStyles: { fillColor: [19, 91, 236] },
            styles: { fontSize: 10 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
        });
        finalY = doc.lastAutoTable.finalY + 15;
    } else {
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("No document data available.", 14, finalY);
        finalY += 15;
    }

    // --- 2. VEHICLE ASSESSMENT ---
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("2. Vehicle Assessment", 14, finalY);
    finalY += 8;

    if (vehicle && vehicle.brandModel) {
        const vehicleData = [
            ["Brand & Model", vehicle.brandModel],
            ["Plate Number", vehicle.plateNumber || "-"],
            ["Year", vehicle.year || "-"],
            ["Physical Condition", vehicle.physicalCondition || "-"],
        ];

        autoTable(doc, {
            startY: finalY,
            head: [["Attribute", "Details"]],
            body: vehicleData,
            theme: 'striped',
            headStyles: { fillColor: [19, 91, 236] },
            styles: { fontSize: 10 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
        });
        finalY = doc.lastAutoTable.finalY + 15;
    } else {
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("No vehicle data available.", 14, finalY);
        finalY += 15;
    }

    // --- 3. VALUATION & PRICING ---
    // If we have pricing logic available or passed down
    // Since Pricing logic is inside PricingCard, we rely on what was passed or we might have to re-calculate?
    // Ideally, Dashboard passed the *result* of pricing.
    // But Dashboard only holds vehicle/doc data.
    // We need to re-run pricing logic or have PricingCard notify Dashboard.
    // For PoC, let's assume we re-calculate or simply show "See System" if not passed.
    // BUT the user wants "Export result".

    // We will assume `pricing` object is passed if available, otherwise we skip.
    if (pricing) {
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text("3. Valuation & Pricing", 14, finalY);
        finalY += 8;

        const priceData = [
            ["Market Price (Base)", pricing.basePrice ? `Rp ${pricing.basePrice.toLocaleString('id-ID')}` : "-"],
            ["Condition Adjustment", pricing.adjustment ? `Rp ${pricing.adjustment.toLocaleString('id-ID')}` : "-"],
            ["Estimated Asset Value", pricing.assetValue ? `Rp ${pricing.assetValue.toLocaleString('id-ID')}` : "-"],
            ["AI Confidence", pricing.confidence ? `${Math.round(pricing.confidence * 100)}%` : "-"],
        ];

        autoTable(doc, {
            startY: finalY,
            head: [["Component", "Value"]],
            body: priceData,
            theme: 'grid',
            headStyles: { fillColor: [40, 167, 69] }, // Green for money
            styles: { fontSize: 10 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } },
        });

        finalY = doc.lastAutoTable.finalY + 10;

        // Legal Disclaimer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Disclaimer: This report is generated by AI (PoC). Values are estimates and require final verification by an appraiser.", 14, finalY + 10);
    }

    doc.save(`Pegadaian_Analytics_${new Date().toISOString().slice(0, 10)}.pdf`);
}
